version: 0.0
os: linux

hooks:
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: root

  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root

  ApplicationStop:
    - location: scripts/application_stop.sh
      runas: root
